name: 'fintech_analytics'
version: '1.0.0'
config-version: 2

profile: 'fintech_analytics'

model-paths: ["models"]

models:
  fintech_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
